function export_tms_to_brainsight_from_txt(inXfmTxt, outBrainsightTxt, varargin)
%EXPORT_TMS_TO_BRAINSIGHT_FROM_TXT Convert SimNIBS transform txt to Brainsight txt.
%
% Goal
%   Read one or more 4x4 SimNIBS affine transforms from text and export a
%   Brainsight trajectory file via a Python subprocess using SimNIBS APIs.
%
% Usage
%   export_tms_to_brainsight_from_txt(inXfmTxt, outBrainsightTxt)
%   export_tms_to_brainsight_from_txt(..., 'PythonExe', pythonExe, 'KeepTmp', tf)
%
% Inputs
%   inXfmTxt (char/string)
%       Path to transform text file. Accepted shapes include `4x4`,
%       `(4*N)x4`, `16xN`, `Nx16`, and flattened `16*N`.
%   outBrainsightTxt (char/string)
%       Output Brainsight trajectory text path.
%   Name-Value:
%       PythonExe (char/string, default "python")
%           Python executable with `simnibs` and `numpy` installed.
%       KeepTmp (logical, default false)
%           Keep the temporary generated Python script for debugging.
%
% Outputs
%   None (writes `outBrainsightTxt`).
%
% Side Effects
%   Writes and executes a temporary Python script, optionally deletes it,
%   and prints the created output path.

    % -------------------- Parse inputs --------------------
    p = inputParser;
    addParameter(p, 'PythonExe', "python", @(x)ischar(x) || isstring(x));
    addParameter(p, 'KeepTmp', false, @(x)islogical(x) && isscalar(x));
    parse(p, varargin{:});
    pythonExe = char(string(p.Results.PythonExe));
    keepTmp   = p.Results.KeepTmp;

    inXfmTxt         = char(string(inXfmTxt));
    outBrainsightTxt = char(string(outBrainsightTxt));

    if ~exist(inXfmTxt, 'file')
        error('Input transform txt not found: %s', inXfmTxt);
    end

    outDir = fileparts(outBrainsightTxt);
    if ~isempty(outDir) && ~exist(outDir, 'dir')
        mkdir(outDir);
    end

    % -------------------- Write temp python script (robust: line-by-line) --------------------
    tmpPy = [tempname '_simnibs_bs_export_from_txt.py'];
    fid = fopen(tmpPy, 'w');
    assert(fid > 0, 'Could not create temporary Python script: %s', tmpPy);

    if ~keepTmp
        cleaner = onCleanup(@() cleanup_tmp(tmpPy)); %#ok<NASGU>
    end

    pyLines = { ...
        'import sys', ...
        'import numpy as np', ...
        'import simnibs', ...
        '', ...
        'in_txt = sys.argv[1]', ...
        'out_txt = sys.argv[2]', ...
        '', ...
        '# Load numeric text (whitespace/tab delimited).', ...
        '# If your file has non-numeric header lines, consider pre-cleaning it or add skiprows/comments handling here.', ...
        'M = np.loadtxt(in_txt, dtype=float)', ...
        'M = np.asarray(M, dtype=float)', ...
        '', ...
        '# Accept formats:', ...
        '#  - 4x4', ...
        '#  - (4*N) x 4   (N blocks of 4 rows)', ...
        '#  - 16 x N or N x 16 (flattened)', ...
        '#  - 1D length 16 or 16*N', ...
        '', ...
        'if M.ndim == 1:', ...
        '    # flattened vector', ...
        '    if M.size == 16:', ...
        '        M = M.reshape((4,4))', ...
        '    elif (M.size % 16) == 0:', ...
        '        M = M.reshape((-1,4,4))', ...
        '    else:', ...
        '        raise ValueError(f"Cannot interpret 1D input of length {M.size} as 4x4 or stack")', ...
        'elif M.ndim == 2:', ...
        '    if M.shape == (4,4):', ...
        '        pass', ...
        '    elif (M.shape[1] == 4) and ((M.shape[0] % 4) == 0):', ...
        '        # (4*N) x 4 -> N x 4 x 4', ...
        '        M = M.reshape((-1,4,4))', ...
        '    elif M.shape[0] == 16:', ...
        '        # 16 x N -> N x 4 x 4', ...
        '        M = M.T.reshape((-1,4,4))', ...
        '    elif M.shape[1] == 16:', ...
        '        # N x 16 -> N x 4 x 4', ...
        '        M = M.reshape((-1,4,4))', ...
        '    else:', ...
        '        raise ValueError(f"Cannot interpret 2D input shape {M.shape} as 4x4 or stack")', ...
        'else:', ...
        '    raise ValueError(f"Cannot interpret input with ndim={M.ndim}")', ...
        '', ...
        '# Write Brainsight file', ...
        'try:', ...
        '    simnibs.brainsight().write(M, out_txt)', ...
        'except Exception:', ...
        '    simnibs.brainsight.write(M, out_txt)', ...
        '', ...
        'print(out_txt)', ...
        };

    for iLine = 1:numel(pyLines)
        fprintf(fid, '%s\n', pyLines{iLine});
    end
    fclose(fid);

    % -------------------- Run python --------------------
    cmd = sprintf('"%s" "%s" "%s" "%s"', pythonExe, tmpPy, inXfmTxt, outBrainsightTxt);
    [status, txt] = system(cmd);

    if status ~= 0
        msg = sprintf(['Brainsight export failed.\n' ...
                       'Command:\n%s\n\n' ...
                       'Temp script:\n%s\n\n' ...
                       'Python output:\n%s'], cmd, tmpPy, txt);
        error(msg);
    end

    fprintf('Brainsight export written: %s\n', strtrim(txt));
end

function cleanup_tmp(f)
    if exist(f, 'file')
        delete(f);
    end
end
