function [M, meta] = import_simnibs_matsimnibs_from_brainsight(inBrainsightTxt, varargin)
%IMPORT_SIMNIBS_MATSIMNIBS_FROM_BRAINSIGHT Import BrainSight trajectory as matsimnibs matrices.
%
% Goal
%   Read a BrainSight export `.txt` and return SimNIBS-compatible 4x4
%   `matsimnibs` transform(s) in MATLAB.
%
% Usage
%   [M, meta] = import_simnibs_matsimnibs_from_brainsight(inBrainsightTxt)
%   [M, meta] = import_simnibs_matsimnibs_from_brainsight(..., 'Name', value, ...)
%
% Inputs
%   inBrainsightTxt (char/string)
%       Path to BrainSight trajectory export text file.
%   Name-Value options
%       PythonExe (char/string, default "python")
%       UseSimnibsPython (logical, default false)
%       Which (char/string: 'targets'|'samples'|'auto'|'both', default 'auto')
%       NameContains (char/string, default "")
%       NameContainsIgnoreCase (logical, default true)
%       NormalizeHeaders (logical, default false)
%       FixS2Q (logical, default true)
%       OutMatFile (char/string, default "")
%       KeepTmp (logical, default false)
%
% Outputs
%   M (4x4xN double)
%       SimNIBS `matsimnibs` matrices. Use `M(:,:,1)` for a single pose.
%   meta (struct)
%       Import metadata including selected block (`targets`/`samples`) and
%       parser/runtime details.
%
% Side Effects
%   Executes a temporary Python script in a subprocess, writes/deletes
%   temporary files, and optionally writes `OutMatFile`.

    p = inputParser;
    addParameter(p,'PythonExe',"python",@(x)ischar(x)||isstring(x));
    addParameter(p,'UseSimnibsPython',false,@(x)islogical(x)&&isscalar(x));
    addParameter(p,'Which','auto',@(x)ischar(x)||isstring(x));
    addParameter(p,'NameContains',"",@(x)ischar(x)||isstring(x));
    addParameter(p,'NameContainsIgnoreCase',true,@(x)islogical(x)&&isscalar(x));
    addParameter(p,'NormalizeHeaders',false,@(x)islogical(x)&&isscalar(x));
    addParameter(p,'FixS2Q',true,@(x)islogical(x)&&isscalar(x));
    addParameter(p,'OutMatFile',"",@(x)ischar(x)||isstring(x));
    addParameter(p,'KeepTmp',false,@(x)islogical(x)&&isscalar(x));
    parse(p,varargin{:});

    pythonExe        = char(string(p.Results.PythonExe));
    useSimnibsPython = p.Results.UseSimnibsPython;
    which            = lower(char(string(p.Results.Which)));
    nameContains     = char(string(p.Results.NameContains));
    nameIgnoreCase   = p.Results.NameContainsIgnoreCase;
    normalizeHeaders = p.Results.NormalizeHeaders;
    fixS2Q           = p.Results.FixS2Q;
    outMatFile       = char(string(p.Results.OutMatFile));
    keepTmp          = p.Results.KeepTmp;

    validWhich = {'auto','targets','samples','both'};
    if ~ismember(which, validWhich)
        error('Which must be one of: auto|targets|samples|both');
    end

    inBrainsightTxt = expand_tilde(char(string(inBrainsightTxt)));
    if ~exist(inBrainsightTxt,'file')
        error('Input Brainsight txt not found: %s', inBrainsightTxt);
    end

    tmpPy = [tempname '_simnibs_import_brainsight_to_json.py'];
    tmpJson = [tempname '_simnibs_import_brainsight_to_json.json'];
    fid = fopen(tmpPy,'w');
    assert(fid>0,'Could not create temp python: %s', tmpPy);

    if ~keepTmp
        cleaner = onCleanup(@() cleanup_tmp_many({tmpPy, tmpJson})); %#ok<NASGU>
    end

    py = { ...
        'import sys, os, json, tempfile', ...
        'import numpy as np', ...
        'from simnibs import brainsight', ...
        '', ...
        'in_txt    = sys.argv[1]', ...
        'which     = sys.argv[2].lower()', ...
        'name_sub  = sys.argv[3]', ...
        'name_ic   = int(sys.argv[4])', ...
        'normhdr   = int(sys.argv[5])', ...
        'fixs2q    = int(sys.argv[6])', ...
        'out_json  = sys.argv[7]', ...
        '', ...
        '# --- read + optional patching ---', ...
        'tmp_in = in_txt', ...
        'with open(in_txt, "r", encoding="utf-8", errors="ignore") as f:', ...
        '    lines = f.readlines()', ...
        '', ...
        'changed = False', ...
        'if fixs2q:', ...
        '    for i, ln in enumerate(lines[:120]):', ...
        '        if ln.startswith("# Coordinate system:") and "NIfTI:S:" in ln:', ...
        '            lines[i] = ln.replace("NIfTI:S:", "NIfTI:Q:", 1)', ...
        '            changed = True', ...
        '            break', ...
        '', ...
        'if normhdr:', ...
        '    for i, ln in enumerate(lines[:220]):', ...
        '        if ln.startswith("# Target Name"):', ...
        '            lines[i] = ln.replace("# Target Name", "# Target_Name")', ...
        '            changed = True', ...
        '        if ln.startswith("# Sample Name"):', ...
        '            lines[i] = ln.replace("# Sample Name", "# Sample_Name")', ...
        '            changed = True', ...
        '        if (ln.startswith("# Target") or ln.startswith("# Sample")) and ("Loc." in ln):', ...
        '            lines[i] = lines[i].replace("Loc. X","Loc.X").replace("Loc. Y","Loc.Y").replace("Loc. Z","Loc.Z")', ...
        '            changed = True', ...
        '', ...
        'if changed:', ...
        '    fd, tmp_in = tempfile.mkstemp(suffix="_brainsight_fixed.txt")', ...
        '    os.close(fd)', ...
        '    with open(tmp_in, "w", encoding="utf-8") as g:', ...
        '        g.writelines(lines)', ...
        '', ...
        'tgt, smp = brainsight().read(tmp_in)', ...
        '', ...
        'def list_names(tms):', ...
        '    try:', ...
        '        return [p.name for p in tms.pos]', ...
        '    except Exception:', ...
        '        return []', ...
        '', ...
        'def list_mats(tms):', ...
        '    mats = []', ...
        '    for p in getattr(tms, "pos", []):', ...
        '        m = np.asarray(getattr(p, "matsimnibs", None), dtype=float)', ...
        '        if m.shape != (4,4):', ...
        '            raise ValueError(f"Expected 4x4 matsimnibs, got {m.shape}")', ...
        '        mats.append(m)', ...
        '    if len(mats) == 0:', ...
        '        return np.zeros((0,4,4), dtype=float), []', ...
        '    return np.stack(mats, axis=0), list_names(tms)', ...
        '', ...
        'tgt_m, tgt_n = list_mats(tgt)', ...
        'smp_m, smp_n = list_mats(smp)', ...
        '', ...
        'picked = which', ...
        'if which == "auto":', ...
        '    if tgt_m.shape[0] > 0:', ...
        '        mats, names, picked = tgt_m, tgt_n, "targets"', ...
        '    else:', ...
        '        mats, names, picked = smp_m, smp_n, "samples"', ...
        'elif which == "targets":', ...
        '    mats, names = tgt_m, tgt_n', ...
        'elif which == "samples":', ...
        '    mats, names = smp_m, smp_n', ...
        'elif which == "both":', ...
        '    mats = np.concatenate([tgt_m, smp_m], axis=0) if (tgt_m.shape[0]+smp_m.shape[0])>0 else np.zeros((0,4,4))', ...
        '    names = (tgt_n or []) + (smp_n or [])', ...
        'else:', ...
        '    raise ValueError("Which must be auto|targets|samples|both")', ...
        '', ...
        'if name_sub:', ...
        '    if name_ic:', ...
        '        needle = str(name_sub).lower()', ...
        '        keep = [i for i,n in enumerate(names) if (n is not None and needle in str(n).lower())]', ...
        '    else:', ...
        '        keep = [i for i,n in enumerate(names) if (n is not None and name_sub in str(n))]', ...
        '    mats = mats[keep,:,:] if len(keep)>0 else np.zeros((0,4,4))', ...
        '    names = [names[i] for i in keep] if len(keep)>0 else []', ...
        '', ...
        'out = {', ...
        '  "picked": picked,', ...
        '  "n": int(mats.shape[0]),', ...
        '  "names": names,', ...
        '  "tmp_in": tmp_in,', ...
        '  "mats_colmajor": mats.transpose(0,2,1).reshape(mats.shape[0],16).tolist()', ...
        '}', ...
        'with open(out_json, "w", encoding="utf-8") as f:', ...
        '    json.dump(out, f)', ...
        'print(f"wrote:{out_json}")', ...
        };

    for i=1:numel(py)
        fprintf(fid,'%s\n',py{i});
    end
    fclose(fid);

    if useSimnibsPython
        runner = 'simnibs_python';
    else
        runner = pythonExe;
    end

    cmd = sprintf('"%s" "%s" "%s" "%s" "%s" "%d" "%d" "%d" "%s"', ...
        runner, tmpPy, inBrainsightTxt, which, nameContains, nameIgnoreCase, normalizeHeaders, fixS2Q, tmpJson);

    [status, txt] = system(cmd);
    if status ~= 0
        error('Brainsight -> SimNIBS import failed.\nCommand:\n%s\n\nPython output:\n%s', cmd, txt);
    end

    if ~exist(tmpJson,'file')
        error('Python command finished but JSON output not found: %s\nPython output:\n%s', tmpJson, txt);
    end

    % Parse JSON file (robust against extra stdout logs/warnings)
    rawJson = fileread(tmpJson);
    S = jsondecode(rawJson);

    meta = struct();
    meta.which = which;
    meta.picked = S.picked;
    meta.n = S.n;
    meta.names = string(S.names);
    meta.tmp_in = string(S.tmp_in);
    meta.python_stdout = string(txt);
    meta.python_cmd = string(cmd);

    if meta.n == 0
        M = zeros(4,4,0);
        return
    end

    % Reconstruct matsimnibs in MATLAB from column-major flatten (per pose)
    A = double(S.mats_colmajor);    % N x 16
    N = size(A,1);
    M = zeros(4,4,N);
    for i=1:N
        M(:,:,i) = reshape(A(i,:),4,4); % already column-major
    end

    if ~isempty(outMatFile)
        outMatFile = expand_tilde(outMatFile);
        save(outMatFile,'M','meta');
    end
end

function s = expand_tilde(s)
    if startsWith(s,'~')
        s = [getenv('HOME') s(2:end)];
    end
end

function cleanup_tmp(f)
    if exist(f,'file'), delete(f); end
end

function cleanup_tmp_many(files)
    for k = 1:numel(files)
        cleanup_tmp(files{k});
    end
end
